### ISSUE TITLE
java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [laymanuel/GravityControl#10]
Hi, I see your plugins can running on the Folia right?
I just try it but it seems didn't work, maybe this is a bug?
----------------------------------------
[Logs: java.lang.UnsupportedOperationException: null](https://paste.ubuntu.com/p/PPvdhnkzcC/)
----------------------------------------

**Comment by xiaoyueyoqwq** [comment]
Well, I found MidnightTale_'s plugins is better~

**Comment by sofianedjerbi** [comment]
You weren't using the latest dev version, which isn't released. Though GravityControl is not made for Folia.
