### ISSUE TITLE
Dripstone and scaffolding duping are not supported 

### ISSUE THREAD

**Issue by sjavi4** [laymanuel/GravityControl#4]
cannot dupe these 2, would you like to add them?

**Comment by e-im** [comment]
I don't think these will be added at this time. This plugin is only meant to enable gravity block duping with an end portal, nothing else. These both look to abuse a different bug which is out of scope. It is possible that at some point I'll make another plugin or expand the scope of this adding multiple modules for different dupes. However, at this time new dupes won't be added.

**Comment by sjavi4** [comment]
> I don't think these will be added at this time. This plugin is only meant to enable gravity block duping with an end portal, nothing else. These both look to abuse a different bug which is out of scope. It is possible that at some point I'll make another plugin or expand the scope of this adding multiple modules for different dupes. However, at this time new dupes won't be added.

Actually dripstone and scaffolding have their falling block states (gravity block under conditions), and this feature also been used in end portal for duping
*dripstone falls when there is no block hanging them
*scaffolding falls when the distance exceeds 6 and without block underneath

**Comment by e-im** [comment]
Sorry. from a quick google I had seen people duping these in other ways. Didn't realize it could be done this way.

If you can get the dripstone/scaffolding to move in the same way a typical gravity block duplication machine works, it is pretty much already supported. Just add dripstone and scaffolding to `blocks` in the configuration file.

For what people are doing now, dropping from 6 blocks up to a fence under the portal, this is not currently supported and is harder to support. It is not nearly as easy to detect this reliably. I'll look into supporting this.

**Comment by e-im** [comment]
This plugin is no longer of any use. Use `allow-unsafe-end-portal-teleportation` in the paper configuration instead.
