### ISSUE TITLE
Lack of momentum when using a "faster" duper

### ISSUE THREAD

**Issue by Froppor** [laymanuel/GravityControl#6]
I'd like to report an issue while using this plugin (Paper 1.19.2-174, no other plugins than WorldEdit/WorldGuard/Dynmap) and utilising a "faster" duper design. I've been using designs from this video:

https://www.youtube.com/watch?v=dtt-HTwikfs

The simplest "43.2K" design properly adds the vanilla momentum to the blocks as they appear in the end, however the "108K" design unfortunately does not. The blocks just appear in the middle of the obsidian platform and fall straight down with little to no momentum. I have of course tested the latter design in 1.19.2 single player and there it seems to work as intended (world download with said design and an accompanying End concrete generator: https://www.mediafire.com/file/mgfjmipswnyxmcc/Concrete_Reactor.zip/file).

Are there any server configuration parameters I should check or is this a current limitation of the plugin? Thanks in advance for your time.

**Comment by e-im** [comment]
That is a limitation of the plugin at this time.

How the plugin works is reimplementing sand duping, not unpatching it. For the slower design, the original maintainer got [these numbers]( https://github.com/e-im/GravityControl/blob/main/src/main/java/one/eim/gravitycontrol/Configuration.java#L38) for appropriate velocity from *somewhere*, I have no idea where.

A workaround would be to implement a similar thing for the faster design (notice no setVelocity call [here](https://github.com/e-im/GravityControl/blob/main/src/main/java/one/eim/gravitycontrol/GravityListener.java#L63)) that isn't a long term fix.

Pretty much all reported issues have been from the attempt to reimplements with API, I think a longer term strategy must be to rework how the plugin functions, falling back to the bukkit reimplementation.

**Comment by Froppor** [comment]
Thank you for the quick reply and explanation. Would it be possible to implement this workaround, despite it not being a long term fix? :)

**Comment by e-im** [comment]
Taking a more thorough look, that workaround won't really work at all. I have an idea for another solution (that will also close #4), but it'll be at least a few days before I work on it.

**Comment by Froppor** [comment]
No worries, already thankful for this plugin, being able to use the other duper designs would just be the cherry on top.

**Comment by e-im** [comment]
Looked into this some more. Unfortunately, not going to get fixed any time soon. It would require reworking the entire plugin to be much more hacky and take a fully different approach. Might as well make it an agent at that point.

**Comment by sofianedjerbi** [comment]
You might want to look into [FoliaFlow](https://github.com/Hynse/FoliaFlow/tree/master) which uses a workaround for Folia that reset block velocity 2 tick after spawning it. That workaround works on Paper too.

**Comment by e-im** [comment]
This plugin is no longer of any use. Use `allow-unsafe-end-portal-teleportation` in the paper configuration instead.
